/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example

import InsertInterval
import ProductExceptSelf
import Trie

class App {
    val greeting: String
        get() {
            return "Hello World!"
        }
}

fun main() {
    val answer =
        maxProduct(intArrayOf(0, 10, 10, 10, 10, 10, 10, 10, 10, 10, -10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 0))
    println(answer)
}
