/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example

import InsertInterval

class App {
    val greeting: String
        get() {
            return "Hello World!"
        }
}

fun main() {
    val run = ThreeSum()
    val sum = run.threeSum(intArrayOf(-1, 0, 1, 2, -1, -4))
    println(sum)
}
