/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example

import InsertInterval

class App {
    val greeting: String
        get() {
            return "Hello World!"
        }
}

fun main() {
    val run = LongestSubstring()
    val max = run.lengthOfLongestSubstring("tmmzuxt")
    println(max)
}
